name: Build and Push Django App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Generate semantic version
      id: semver
      run: |
        echo "Fetching tags..."
        git fetch --tags
        
        echo "Current git tags:"
        git tag -l
        
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $latest_tag"
        
        latest_version=${latest_tag#v}
        echo "Latest version (without v): $latest_version"
        
        IFS='.' read -r major minor patch <<< "$latest_version"
        echo "Parsed version: major=$major, minor=$minor, patch=$patch"
        
        patch=$((patch + 1))
        echo "Incremented patch: $patch"
        
        new_version="$major.$minor.$patch"
        echo "New version: $new_version"
        
        echo "VERSION=$new_version" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/todoapp:${{ steps.semver.outputs.VERSION }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/todoapp:${{ steps.semver.outputs.VERSION }}