name: Build and Push Django App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth:   1 # Fetch all history for all tags and branches

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Generate semantic version
      id: semver
      run: |
        # Get the latest tag
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        
        # Remove the 'v' prefix if present
        latest_version=${latest_tag#v}
        
        # Split the version into major, minor, and patch
        IFS='.' read -r major minor patch <<< "$latest_version"
        
        # Increment the patch version
        patch=$((patch + 1))
        
        # Create the new version
        new_version="$major.$minor.$patch"
        
        echo "VERSION=$new_version" >> $GITHUB_OUTPUT
        echo "New version: $new_version"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/todoapp:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/todoapp:${{ steps.semver.outputs.VERSION }}


          


