name: Deploy Todo API

on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t abudev22/todo-api.
        docker push abudev22/t:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Create CodeDeploy deployment
      run: |
        aws deploy create-deployment \
          --application-name  api-deploy\
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name EC2-code-deploy \
          --description "Deploy Todo API" \
          --github-location repository=AbuDev22/todoApp-django,commitId=${{ github.sha }}

